<?php
return [
    'leitores' => [
        [
            'id' => 1,
            'nome' => 'Pedro Teixeira',
            'cpf' => '11122233344',
            'email' => 'pedroteixeira@escola.com',
            'nascimento' => '2010-05-10',
            'tipo' => 'aluno',
        ],
        [
            'id' => 2,
            'nome' => 'Rafaela Nogueira',
            'cpf' => '22233344455',
            'email' => 'rafaelanogueira@escola.com',
            'nascimento' => '2008-03-02',
            'tipo' => 'aluno',
        ],
        [
            'id' => 3,
            'nome' => 'Sarah Gontijo',
            'cpf' => '33344455566',
            'email' => 'sarahgontijo@escola.com',
            'nascimento' => '1985-11-20',
            'tipo' => 'professor',
        ],
    ],
    'livros' => [
        [
            'id' => 1,
            'titulo' => 'Dom Casmurro',
            'isbn' => '9788501000011',
            'autor' => 'Machado de Assis',
            'categoria' => 'Romance',
            'total' => 3,
            'disponiveis' => 2,
        ],
        [
            'id' => 2,
            'titulo' => 'O Pequeno Príncipe',
            'isbn' => '9788501000028',
            'autor' => 'Antoine de Saint-Exupéry',
            'categoria' => 'Infantojuvenil',
            'total' => 2,
            'disponiveis' => 1,
        ],
        [
            'id' => 3,
            'titulo' => 'Capitães da Areia',
            'isbn' => '9788501000035',
            'autor' => 'Jorge Amado',
            'categoria' => 'Romance',
            'total' => 1,
            'disponiveis' => 0,
        ],
        [
            'id' => 4,
            'titulo' => 'Vidas Secas',
            'isbn' => '9788501000042',
            'autor' => 'Graciliano Ramos',
            'categoria' => 'Romance',
            'total' => 2,
            'disponiveis' => 1,
        ],
    ],
    'emprestimos' => [
        [
            'id' => 1,
            'id_leitor' => 2,
            'id_livro' => 1,
            'data' => '2026-10-01',
            'prevista' => '2026-10-15',
            'devolucao' => null,
            'status' => 'ativo',
        ],
        [
            'id' => 2,
            'id_leitor' => 2,
            'id_livro' => 2,
            'data' => '2026-10-01',
            'prevista' => '2026-10-15',
            'devolucao' => null,
            'status' => 'ativo',
        ],
        [
            'id' => 3,
            'id_leitor' => 2,
            'id_livro' => 3,
            'data' => '2026-10-01',
            'prevista' => '2026-10-15',
            'devolucao' => null,
            'status' => 'ativo',
        ],
        [
            'id' => 4,
            'id_leitor' => 3,
            'id_livro' => 4,
            'data' => '2026-08-01',
            'prevista' => '2026-08-15',
            'devolucao' => '2026-08-22',
            'status' => 'devolvido',
        ],
        [
            'id' => 5,
            'id_leitor' => 1,
            'id_livro' => 4,
            'data' => '2026-09-01',
            'prevista' => '2026-09-15',
            'devolucao' => null,
            'status' => 'ativo',
        ],
    ],
    'reservas' => [
        [
            'id' => 1,
            'id_leitor' => 2,
            'id_livro' => 3,
            'data' => '2026-10-02',
            'status' => 'ativa',
        ],
    ],
    'multas' => [
        [
            'id' => 1,
            'id_emprestimo' => 4,
            'dias_atraso' => 7,
            'valor' => 3.5,
            'status' => 'pendente',
        ],
    ],
];
